In [3]:
train_data, train_label, valid_data, valid_label = load_mnist()

download mnist dataset...
100.000000% completed

In [2]:
from load_mnist import load_mnist

In [4]:
print train_data[0]

[[[ 0.  0.  0. ...,  0.  0.  0.]]

 [[ 0.  0.  0. ...,  0.  0.  0.]]

 [[ 0.  0.  0. ...,  0.  0.  0.]]

 ..., 
 [[ 0.  0.  0. ...,  0.  0.  0.]]

 [[ 0.  0.  0. ...,  0.  0.  0.]]

 [[ 0.  0.  0. ...,  0.  0.  0.]]]


In [5]:
print type(train_data)

<type 'numpy.ndarray'>


In [6]:
print train_data.size


39200000


In [7]:
print train_data.shape

(28, 28, 1, 50000)


In [59]:
f = gzip.open('../data/mnist/mnist.pkl.gz', 'rb')

In [52]:
import gzip

In [53]:
f = gzip.open('../data/mnist/mnist.pkl.gz', 'rb')

In [60]:
train_set, valid_set, test_set = cPickle.load(f)

In [57]:
import cPickle

In [58]:
train_set, valid_set, test_set = cPickle.load(f)

EOFError: 

In [61]:
print train_data.shape

(28, 28, 1, 50000)


In [62]:
train_data = train_set[0]

In [63]:
print train_data.shape

(50000, 784)


In [64]:
train_data = np.reshape(train_data, (-1, 28, 28, 1))

In [18]:
import numpy as np

In [66]:
train_data = np.reshape(train_data, (-1, 28, 28, 1))

In [65]:
print train_data.shape

(50000, 28, 28, 1)


In [21]:
xx=np.transpose(train_data, (1, 2, 3, 0))

In [22]:
print xx.shape

(28, 28, 1, 50000)


In [23]:
train_data = np.transpose(train_data, (1, 2, 3, 0)) * 255

In [24]:
print train_data.shape

(28, 28, 1, 50000)


In [27]:
print train_data[:,:,:,0].shape

(28, 28, 1)


In [68]:
train_label = train_set[1]

In [69]:
print train_label.shape

(50000,)


In [30]:
print train_label[0:9]

[5 0 4 1 9 2 1 3 1]


In [31]:
train_label = np.reshape(train_label, (1, -1))

In [32]:
print train_label.shape

(1, 50000)


In [71]:
from model.initial_LeNet import initial_LeNet

In [72]:
lr = [0.01, 0.001]

In [73]:
cnn.train(train_data, train_label, lr, epoch=2, batch_size=100)

ValueError: need more than 1 value to unpack

In [37]:
cnn = initial_LeNet()

In [38]:
cnn.train(train_data, train_label, lr, epoch=2, batch_size=100)

epoch: 0, batch: 0, time: 0.814309 sec, obj: 2.305930
epoch: 0, batch: 1, time: 0.849802 sec, obj: 2.297800
epoch: 0, batch: 2, time: 0.799964 sec, obj: 2.291689
epoch: 0, batch: 3, time: 0.789646 sec, obj: 2.284155
epoch: 0, batch: 4, time: 0.745939 sec, obj: 2.276849
epoch: 0, batch: 5, time: 0.828629 sec, obj: 2.271398
epoch: 0, batch: 6, time: 0.775788 sec, obj: 2.265837
epoch: 0, batch: 7, time: 0.776466 sec, obj: 2.256450
epoch: 0, batch: 8, time: 0.806900 sec, obj: 2.246222
epoch: 0, batch: 9, time: 0.780126 sec, obj: 2.233549
epoch: 0, batch: 10, time: 0.827893 sec, obj: 2.218699
epoch: 0, batch: 11, time: 0.791678 sec, obj: 2.200546
epoch: 0, batch: 12, time: 0.758342 sec, obj: 2.179327
epoch: 0, batch: 13, time: 0.776978 sec, obj: 2.161222
epoch: 0, batch: 14, time: 0.798485 sec, obj: 2.140451
epoch: 0, batch: 15, time: 0.754741 sec, obj: 2.108175
epoch: 0, batch: 16, time: 0.767171 sec, obj: 2.059309
epoch: 0, batch: 17, time: 0.853257 sec, obj: 2.006440
epoch: 0, batch: 18,

cnn/conv_net.py:154: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  sub_train_data = train_data[:, :, :, batch_idx * batch_size:(batch_idx + 1) * batch_size]
cnn/conv_net.py:155: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  sub_train_label = train_label[:, batch_idx * batch_size:(batch_idx + 1) * batch_size]
cnn/conv_net.py:151: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  sub_train_data = train_data[:, :, :, batch_idx * batch_size:]



epoch: 0, batch: 499, time: 0.696904 sec, obj: 0.265553
epoch: 1, batch: 0, time: 0.707815 sec, obj: 0.265285
epoch: 1, batch: 1, time: 0.702449 sec, obj: 0.265172
epoch: 1, batch: 2, time: 0.711859 sec, obj: 0.264862
epoch: 1, batch: 3, time: 0.712409 sec, obj: 0.264410
epoch: 1, batch: 4, time: 0.707153 sec, obj: 0.264142
epoch: 1, batch: 5, time: 0.697966 sec, obj: 0.263775
epoch: 1, batch: 6, time: 0.695545 sec, obj: 0.263463
epoch: 1, batch: 7, time: 0.713330 sec, obj: 0.263111
epoch: 1, batch: 8, time: 0.688467 sec, obj: 0.262780
epoch: 1, batch: 9, time: 0.697215 sec, obj: 0.262502
epoch: 1, batch: 10, time: 0.695987 sec, obj: 0.262166
epoch: 1, batch: 11, time: 0.686247 sec, obj: 0.261742
epoch: 1, batch: 12, time: 0.713985 sec, obj: 0.261646
epoch: 1, batch: 13, time: 0.691127 sec, obj: 0.261403
epoch: 1, batch: 14, time: 0.701561 sec, obj: 0.261019
epoch: 1, batch: 15, time: 0.698154 sec, obj: 0.260686
epoch: 1, batch: 16, time: 0.697426 sec, obj: 0.260343
epoch: 1, batch: 1

cnn/conv_net.py:152: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  sub_train_label = train_label[:, batch_idx * batch_size:]


In [39]:
cnn.layers

[{'bias': array([[[[ -3.46310997e-04,   3.48715198e-04,  -3.02043097e-04,
             -1.26305745e-04,   4.01951863e-05,   3.44067936e-05,
             -6.81077329e-04,  -1.45401236e-04,   1.52329513e-04,
             -3.32889155e-04,  -4.20781135e-04,   3.53557794e-04,
             -3.64752808e-04,   6.64410392e-04,  -4.35261796e-04,
             -3.67651349e-04,  -5.11016388e-04,  -4.96787507e-05,
             -2.88020052e-04,  -3.37030859e-04]]]]),
  'grad': [array([[[[ -1.69909882e-11,   1.00389130e-10,   2.61096303e-08, ...,
              -2.90827087e-11,  -2.54784861e-08,  -1.01804129e-10]],
   
           [[ -3.58954444e-12,  -1.25248647e-11,   1.39555895e-08, ...,
              -2.10993032e-10,  -3.26434682e-08,  -7.56390059e-10]],
   
           [[  2.34375380e-11,   1.63334513e-11,  -4.65354361e-09, ...,
              -4.34847133e-10,   4.42163078e-08,  -1.93914920e-09]],
   
           ..., 
           [[ -2.36142557e-11,   4.56848589e-11,   7.77189003e-09, ...,
           

In [40]:
print cnn.layers

[{'stride': 1, 'bias': array([[[[ -3.46310997e-04,   3.48715198e-04,  -3.02043097e-04,
           -1.26305745e-04,   4.01951863e-05,   3.44067936e-05,
           -6.81077329e-04,  -1.45401236e-04,   1.52329513e-04,
           -3.32889155e-04,  -4.20781135e-04,   3.53557794e-04,
           -3.64752808e-04,   6.64410392e-04,  -4.35261796e-04,
           -3.67651349e-04,  -5.11016388e-04,  -4.96787507e-05,
           -2.88020052e-04,  -3.37030859e-04]]]]), 'weights': array([[[[ -3.11100233e-02,   3.42949812e-02,   2.87327064e-03,
            4.19560348e-02,  -2.00106426e-02,  -2.39365126e-02,
           -2.81007425e-02,   3.71355048e-02,  -2.63043669e-03,
           -2.69325805e-02,  -2.03707378e-02,   2.91566036e-02,
           -4.04319084e-02,   9.20335648e-04,  -7.59315839e-03,
           -8.23334139e-03,   4.37533865e-02,   3.30515143e-02,
            1.97841654e-02,  -3.69176740e-02]],

        [[  1.54778352e-02,  -2.34768941e-03,   1.01736911e-02,
            5.28628787e-02,  -6.06

In [41]:
print cnn.layers[0]

{'stride': 1, 'bias': array([[[[ -3.46310997e-04,   3.48715198e-04,  -3.02043097e-04,
           -1.26305745e-04,   4.01951863e-05,   3.44067936e-05,
           -6.81077329e-04,  -1.45401236e-04,   1.52329513e-04,
           -3.32889155e-04,  -4.20781135e-04,   3.53557794e-04,
           -3.64752808e-04,   6.64410392e-04,  -4.35261796e-04,
           -3.67651349e-04,  -5.11016388e-04,  -4.96787507e-05,
           -2.88020052e-04,  -3.37030859e-04]]]]), 'weights': array([[[[ -3.11100233e-02,   3.42949812e-02,   2.87327064e-03,
            4.19560348e-02,  -2.00106426e-02,  -2.39365126e-02,
           -2.81007425e-02,   3.71355048e-02,  -2.63043669e-03,
           -2.69325805e-02,  -2.03707378e-02,   2.91566036e-02,
           -4.04319084e-02,   9.20335648e-04,  -7.59315839e-03,
           -8.23334139e-03,   4.37533865e-02,   3.30515143e-02,
            1.97841654e-02,  -3.69176740e-02]],

        [[  1.54778352e-02,  -2.34768941e-03,   1.01736911e-02,
            5.28628787e-02,  -6.063

In [42]:
for i in cnn.layers:
    print i

{'stride': 1, 'bias': array([[[[ -3.46310997e-04,   3.48715198e-04,  -3.02043097e-04,
           -1.26305745e-04,   4.01951863e-05,   3.44067936e-05,
           -6.81077329e-04,  -1.45401236e-04,   1.52329513e-04,
           -3.32889155e-04,  -4.20781135e-04,   3.53557794e-04,
           -3.64752808e-04,   6.64410392e-04,  -4.35261796e-04,
           -3.67651349e-04,  -5.11016388e-04,  -4.96787507e-05,
           -2.88020052e-04,  -3.37030859e-04]]]]), 'weights': array([[[[ -3.11100233e-02,   3.42949812e-02,   2.87327064e-03,
            4.19560348e-02,  -2.00106426e-02,  -2.39365126e-02,
           -2.81007425e-02,   3.71355048e-02,  -2.63043669e-03,
           -2.69325805e-02,  -2.03707378e-02,   2.91566036e-02,
           -4.04319084e-02,   9.20335648e-04,  -7.59315839e-03,
           -8.23334139e-03,   4.37533865e-02,   3.30515143e-02,
            1.97841654e-02,  -3.69176740e-02]],

        [[  1.54778352e-02,  -2.34768941e-03,   1.01736911e-02,
            5.28628787e-02,  -6.063

In [43]:
for i in cnn.layers:
    print i.layer_params
    

AttributeError: 'dict' object has no attribute 'layer_params'

In [ ]:
print cnn

In [ ]:
print type(cnn)

In [ ]:
1+2

In [ ]:
print 1+2

In [44]:
 l_weights = np.random.normal(0, 0.1, (5, 5, 1, 3))

In [45]:
print l_weights


[[[[  7.04699040e-02   1.45345258e-02   3.89729657e-02]]

  [[  1.66901365e-01   2.72883805e-01   1.44887072e-01]]

  [[ -2.44215293e-01  -4.02392414e-03  -9.71105216e-02]]

  [[ -4.83604735e-02  -6.81502456e-02   4.74925622e-02]]

  [[  6.45171551e-02   7.47025691e-03   8.01123813e-02]]]


 [[[ -1.52136468e-02   9.96831105e-02   4.05388706e-02]]

  [[  4.20034194e-02  -6.73293456e-02   6.32746725e-02]]

  [[  1.80880727e-01   6.06064288e-02  -7.60555418e-02]]

  [[ -4.94981810e-03  -2.11675333e-02  -3.14447251e-02]]

  [[ -6.92162097e-02  -8.25749300e-02  -2.94572390e-02]]]


 [[[  5.99619969e-02  -1.24127582e-01   5.22440686e-02]]

  [[  3.28944631e-02   8.23258445e-04   1.40195621e-01]]

  [[  1.75364949e-02  -7.19129963e-02   2.06999528e-01]]

  [[  7.56100764e-02   6.15184356e-03  -9.25110940e-02]]

  [[ -6.76162752e-02   1.14027679e-03   1.74650168e-01]]]


 [[[  1.83119953e-01  -1.23242867e-01  -2.74548994e-01]]

  [[ -1.27320422e-01   1.18159308e-02   1.60530181e-01]]

  [[  1.

In [46]:
print l_weights.shape

(5, 5, 1, 3)
